spring:
  application:
    name: SpringBoot_properties_yaml_asynchronous_taskScheduling
  datasource:
    url: jdbc:h2:mem:testdb
    password: 123
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path=/swagger-ui.html

example:
  string: |
    Salom .properties file
    WWWWW
    wertyui
    fghjiuytr
  languages:
    - Java
    - Kotlin
    - Go
    - C++
  languages2: ['Java', 'Kotlin', 'Go', 'C++']
  numbers: {'one':1, 'two':2, 'three':3}

people:
  person[0]:
    id: 1
    firstName: Ali
    lastName: Aliyev
    fullName: ${people.person[0].firstName} ${people.person[0].lastName}
    age: 23
  person[1]:
    id: 2
    firstName: Vali
    lastName: Valiyev
    fullName: ${people.person[1].firstName} ${people.person[1].lastName}
    age: 25